---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-runtime-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          securityContext:
            runAsUser: null
            runAsGroup: null
          containers:
            - name: package-runtime
              securityContext:
                runAsUser: null
                runAsGroup: null
              volumeMounts:
                - mountPath: /templates/xnamespace
                  name: xnamespace-templates
                  readOnly: true
                - mountPath: /templates/xtestplatformcluster
                  name: xtestplatformcluster-templates
                  readOnly: true
          volumes:
            - name: xnamespace-templates
              configMap:
                name: xnamespace-templates
            - name: xtestplatformcluster-templates
              configMap:
                name: xtestplatformcluster-templates

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-patch-and-transform@sha256:ffb9d3e654ee5f1ec73ee5d0ddaadd94d5f2d0bef27231f155f6492c7f14460b
  runtimeConfigRef:
    name: function-runtime-config

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-go-templating@sha256:c42594df57f8a284cf119f2d664e1665b3e9ac84d2d55e7a65d547fa5709aa19
  runtimeConfigRef:
    name: function-runtime-config

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-auto-ready
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-auto-ready@sha256:dc5f9a5db1fb291bc6b6b4f2cce5ca77737bda56411404944e07221b9440a9ae
  runtimeConfigRef:
    name: function-runtime-config
