---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-runtime-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          securityContext:
            runAsUser: null
            runAsGroup: null
          containers:
            - name: package-runtime
              securityContext:
                runAsUser: null
                runAsGroup: null
              volumeMounts:
                - mountPath: /templates/xnamespace
                  name: xnamespace-templates
                  readOnly: true
                - mountPath: /templates/xtestplatformcluster
                  name: xtestplatformcluster-templates
                  readOnly: true
          volumes:
            - name: xnamespace-templates
              configMap:
                name: xnamespace-templates
            - name: xtestplatformcluster-templates
              configMap:
                name: xtestplatformcluster-templates

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-patch-and-transform@sha256:22e4aafa2a3cde94e5ce48a92ead6672cca1438db7955a62b7b72e5bf070b1d2
  runtimeConfigRef:
    name: function-runtime-config

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-go-templating@sha256:787c86cc7e273f6d1fe693b8110855b8dc423fa126d00b992fe62ed88230ceae
  runtimeConfigRef:
    name: function-runtime-config

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-auto-ready
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-auto-ready@sha256:9a5bfda5a076c04776a41b9c82b6b84dc6c82e67db17a355d77ad71e8ba6e7a9
  runtimeConfigRef:
    name: function-runtime-config
