---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-runtime-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          securityContext:
            runAsUser: null
            runAsGroup: null
          containers:
            - name: package-runtime
              securityContext:
                runAsUser: null
                runAsGroup: null
              volumeMounts:
                - mountPath: /templates/xnamespace
                  name: xnamespace-templates
                  readOnly: true
                - mountPath: /templates/xtestplatformcluster
                  name: xtestplatformcluster-templates
                  readOnly: true
          volumes:
            - name: xnamespace-templates
              configMap:
                name: xnamespace-templates
            - name: xtestplatformcluster-templates
              configMap:
                name: xtestplatformcluster-templates

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-patch-and-transform@sha256:230337a615c0fdbcf6d54fd43753fa879fd7500ed9c86850e7f9fccf41508ce3
  runtimeConfigRef:
    name: function-runtime-config

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-go-templating@sha256:e87a6489d488725953828c247ab902b03ff8808a167841ee173bbb0815b7b1f0
  runtimeConfigRef:
    name: function-runtime-config

---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-auto-ready
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/function-auto-ready@sha256:520b660a22350ba00bd0fbe141df35554f227c5342aa248546ef723b7899f1c2
  runtimeConfigRef:
    name: function-runtime-config
