---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-kubernetes
  namespace: crossplane-system

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/provider-kubernetes@sha256:5c963d3b725daae5c198032db3e458a0b6747e1ed4b2bf2fb332c8a92a7eb2fd
  runtimeConfigRef:
    name: provider-kubernetes-runtime-config

---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes-runtime-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: provider-kubernetes
          securityContext:
            runAsUser: null
            runAsGroup: null
          containers:
            - name: package-runtime
              securityContext:
                runAsUser: null
                runAsGroup: null
              args:
                - '--sanitize-secrets'
                - '--enable-watches'
