---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-kubernetes
  namespace: crossplane-system

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: quay.io/konflux-ci/crossplane-components/provider-kubernetes@sha256:2ea5be1d6c82090d0211c092e902bf02c5daa2572ba7ffc20bebe4c41efc55a1
  runtimeConfigRef:
    name: provider-kubernetes-runtime-config

---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes-runtime-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: provider-kubernetes
          securityContext:
            runAsUser: null
            runAsGroup: null
          containers:
            - name: package-runtime
              securityContext:
                runAsUser: null
                runAsGroup: null
              args:
                - '--sanitize-secrets'
                - '--enable-watches'
