apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: crossplane-helm
    repo: oci://quay.io/konflux-ci/crossplane-components
    version: 0.1.249+477aa57
    releaseName: crossplane
    namespace: crossplane-system
    valuesFile: values.yaml

resources:
  - namespaces.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
