---
nameOverride: crossplane
replicas: 1
leaderElection: false

rbacManager:
  replicas: 1
  leaderElection: false

image:
  repository: quay.io/konflux-ci/crossplane-components@sha256:d3695fc6c385a458becd0da74a016e541e18d2e7b335d724189218fd07e7f739
  tag: ""
  ignoreTag: true
  pullPolicy: IfNotPresent

provider:
  packages: []

function:
  packages: []

securityContextCrossplane:
  runAsNonRoot: true
  runAsUser: null
  runAsGroup: null

securityContextRBACManager:
  runAsNonRoot: true
  runAsUser: null
  runAsGroup: null

customAnnotations:
  ignore-check.kube-linter.io/env-var-secret: >-
    The env variables only contain the name of Secrets to be mounted
