---
nameOverride: crossplane
replicas: 1
leaderElection: false

rbacManager:
  deploy: false

image:
  repository: quay.io/konflux-ci/crossplane-components@sha256:65ff41e44800adae41e75bda50eb42bb32d511bc1e35b9177e9a4bbd0317a486
  tag: ""
  ignoreTag: true
  pullPolicy: IfNotPresent

provider:
  packages: []

function:
  packages: []

securityContextCrossplane:
  runAsNonRoot: true
  runAsUser: null
  runAsGroup: null

customAnnotations:
  ignore-check.kube-linter.io/env-var-secret: >-
    The env variables only contain the name of Secrets to be mounted
