---
nameOverride: crossplane
replicas: 1
leaderElection: false

rbacManager:
  replicas: 1
  leaderElection: false

image:
  repository: quay.io/konflux-ci/crossplane-components@sha256:e517e8da85796c269b479bd86dd4bf581f88bd3b5bcf1fabbece6b2a8271beb6
  tag: ""
  ignoreTag: true
  pullPolicy: IfNotPresent

provider:
  packages: []

function:
  packages: []

securityContextCrossplane:
  runAsNonRoot: true
  runAsUser: null
  runAsGroup: null

securityContextRBACManager:
  runAsNonRoot: true
  runAsUser: null
  runAsGroup: null

customAnnotations:
  ignore-check.kube-linter.io/env-var-secret: >-
    The env variables only contain the name of Secrets to be mounted
