apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
kind: ExtraResources
requirements:
  envcfg:
    apiVersion: apiextensions.crossplane.io/v1beta1
    kind: EnvironmentConfig
    matchName: envcfg

---
{{- $resource_annotations := .observed.composite.resource.metadata.annotations }}
{{- if .extraResources.envcfg.items }}
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: ec
  name: managed-{{ .observed.composite.resource.metadata.name }}
spec:
  forProvider:
    manifest:
      apiVersion: ci.openshift.io/v1
      kind: EphemeralCluster
      metadata:
        name: {{ .observed.composite.resource.metadata.name }}
        namespace: ephemeral-cluster
        annotations:
          ephemeralcluster.ci.openshift.io/konflux-tenant: {{ .observed.composite.resource.spec.claimRef.namespace }}
          ephemeralcluster.ci.openshift.io/konflux-cluster: {{ (first .extraResources.envcfg.items).resource.data.clusterName }}
{{ if ne $resource_annotations nil }}
  {{ $pipeline_run_name := index $resource_annotations "ephemeralcluster.ci.openshift.io/pipeline-run-name" }}
  {{ $task_run_name := index $resource_annotations "ephemeralcluster.ci.openshift.io/task-run-name" }}
          ephemeralcluster.ci.openshift.io/task-run-name: {{ $task_run_name }}
  {{- if ne $pipeline_run_name nil }}
          ephemeralcluster.ci.openshift.io/pipeline-run-name: {{ $pipeline_run_name }}
  {{- end }}
{{ end }}
      spec:
        ciOperator: {{ .observed.composite.resource.spec.ciOperator|toPrettyJson }}
{{- if hasKey .observed.composite.resource.spec "tearDownCluster" }}
        tearDownCluster: {{ .observed.composite.resource.spec.tearDownCluster }}
{{- end }}
  readiness:
    policy: DeriveFromCelQuery
    celQuery: |
      has(object.status) && has(object.status.conditions) &&
      object.status.conditions.exists(c, c.type == 'ClusterReady' && c.status == 'True')
  watch: true
  providerConfigRef:
    name: testplatform-kubernetes-provider-config
{{- end }}
