{{ $secretRef := default "pending" .observed.resources.ec.resource.status.atProvider.manifest.status.secretRef -}}
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: credentials
  name: credentials-{{ .observed.composite.resource.metadata.name }}
spec:
  managementPolicies:
    - Observe
  forProvider:
    manifest:
      apiVersion: v1
      kind: Secret
      metadata:
        name: {{ $secretRef }}
        namespace: ephemeral-cluster
  connectionDetails:
    - apiVersion: v1
      kind: Secret
      namespace: ephemeral-cluster
      name: {{ $secretRef }}
      fieldPath: data.kubeconfig
      toConnectionSecretKey: kubeconfig
    - apiVersion: v1
      kind: Secret
      namespace: ephemeral-cluster
      name: {{ $secretRef }}
      fieldPath: data.kubeAdminPassword
      toConnectionSecretKey: kubeAdminPassword
  writeConnectionSecretToRef:
    namespace: crossplane-connections
    name: credentials-{{ .observed.composite.resource.metadata.name }}
  watch: true
  providerConfigRef:
    name: testplatform-kubernetes-provider-config
